### ISSUE TITLE
Občas při přechodu do modulu vyvolá výjimku

### ISSUE THREAD

**Issue by malinajan** [kmzbrnoI/hJOPrcsDebugger#11]
... a aplikace spadne. Dělá opravdu jen občas.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: kmzbrnoI.hjoprcsdebugger, PID: 31849
    java.lang.RuntimeException: Unable to resume activity {kmzbrnoI.hjoprcsdebugger/kmzbrnoI.hjoprcsdebugger.ui.serverConnector.ServerConnectorActivity}: kotlin.KotlinNullPointerException
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3822)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: kotlin.KotlinNullPointerException
        at kmzbrnoI.hjoprcsdebugger.storage.ServerDb.loadServers(ServerDb.kt:33)
        at kmzbrnoI.hjoprcsdebugger.storage.ServerDb.<init>(ServerDb.kt:29)
        at kmzbrnoI.hjoprcsdebugger.storage.ServerDb$Companion.getInstance(ServerDb.kt:21)
        at kmzbrnoI.hjoprcsdebugger.storage.ServerDb$Companion.getInstance$default(ServerDb.kt:19)
        at kmzbrnoI.hjoprcsdebugger.ui.serverConnector.ServerConnector.start(ServerConnector.kt:73)
        at kmzbrnoI.hjoprcsdebugger.ui.serverConnector.ServerConnector.onResume(ServerConnector.kt:55)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2649)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:2625)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:268)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:479)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:468)
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:195)
        at android.app.Activity.performResume(Activity.java:7325)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 

```

**Comment by NavratilovaH** [comment]
Tohle je taky snad resolved. Kdybys na to ještě narazil, tak napiš.

**Comment by malinajan** [comment]
Není resolved, poslal jsem video v PM.

**Comment by NavratilovaH** [comment]
Tak teď resolved.
