### ISSUE TITLE
Modul

### ISSUE THREAD

**Issue by malinajan** [kmzbrnoI/hJOPrcsDebugger#4]
* [x] Zrušit potvrzování nastavení výstupu. Tohle není kritická operace, potvrzování akorát zdržuje.
* [x] V názvu aktivity opět zobrazit adresu modulu.
* [x] Když otevřu jeden modul, pak jdu zpět, pak jiný modul a pak jdu zpět, nedostanu se zpět na výber modulů, ale na nastavování původního modulu.
* [x] Při aktivaci a pak deaktivaci výstupu dostávám výjimku (udělalo jen jednou, podruhé už ok, možná se to stalo při situaci popsané v předchozím bodu):

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: kmzbrnoI.hjoprcsdebugger, PID: 5832
    java.lang.IllegalStateException: MediaPlayer.create(paren…nager.TYPE_NOTIFICATION)) must not be null
        at kmzbrnoI.hjoprcsdebugger.ui.moduleInfo.ModuleAdapter.onCreateViewHolder(ModuleAdapter.kt:45)
        at kmzbrnoI.hjoprcsdebugger.ui.moduleInfo.ModuleAdapter.onCreateViewHolder(ModuleAdapter.kt:20)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:20693)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20693)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20693)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20693)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:446)
        at android.view.View.layout(View.java:20693)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20693)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20693)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
        at android.view.View.layout(View.java:20693)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2799)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2316)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

* [x] S-COM: není třeba potvrzovat stav volnou "Yes", stačí kliknout na příslušný řádek. Místo "No" stačí tlačítko zpět.
* [x] S-COM: zobrazit návěst "0" modře, jakoukoliv jinou bíle.
* [x] Pokud má výstup typu "B" jiný stav, než 0 nebo 1, umožnit změnit stav i tak a to na 0. Momentálně neumožní změnit stav.
* [x] Měnit stav jen při kliku na obdélníček výstupu, nikoliv na celý řádek (pokud to není super-náročné).

**Comment by NavratilovaH** [comment]
S-COM: zobrazit návěst "0" modře, jakoukoliv jinou bíle. : Bílá na bílém pozadí nepůjde vidět, nějaká jiná barva by být nemohla?

**Comment by NavratilovaH** [comment]
Zrušit potvrzování nastavení výstupu. Tohle není kritická operace, potvrzování akorát zdržuje.: když je jen 1 a 0 (výstupy I a B) tak prostě jen změnit bez dotazu?

**Comment by NavratilovaH** [comment]
Pokud má výstup typu "B" jiný stav, než 0 nebo 1, umožnit změnit stav i tak a to na 0. Momentálně neumožní změnit stav.: tzn ať je tam cokoli vždycky poslat 0 a pokud je 0 poslat 1?

**Comment by malinajan** [comment]
> S-COM: zobrazit návěst "0" modře, jakoukoliv jinou bíle. : Bílá na bílém pozadí nepůjde vidět, nějaká jiná barva by být nemohla?

Určitě, mohla. Třeba oranžová nebo růžová, je to celkem jedno.

**Comment by malinajan** [comment]
> Zrušit potvrzování nastavení výstupu. Tohle není kritická operace, potvrzování akorát zdržuje.: když je jen 1 a 0 (výstupy I a B) tak prostě jen změnit bez dotazu?

Ano.

**Comment by malinajan** [comment]
> Pokud má výstup typu "B" jiný stav, než 0 nebo 1, umožnit změnit stav i tak a to na 0. Momentálně neumožní změnit stav.: tzn ať je tam cokoli vždycky poslat 0 a pokud je 0 poslat 1?

Ano.

**Comment by NavratilovaH** [comment]
Zdá se mi, že už to funguje, teda alespoň mě to nedělalo to co dřív. Vyzkoušíš prosím?

**Comment by malinajan** [comment]
> Zdá se mi, že už to funguje, teda alespoň mě to nedělalo to co dřív. Vyzkoušíš prosím?

Funguje.

**Comment by malinajan** [comment]
Výjimka popsaná v prvním příspěvku pořád nastává.

**Comment by NavratilovaH** [comment]
Fixed.
